import React from 'react';

const About = () => {
  return (
    <div className="max-w-2xl mx-auto py-12">
      <h1 className="text-3xl font-bold uppercase tracking-wider text-black mb-6">About GramPickup</h1>
      
      <div className="space-y-6 text-sm text-gray-600 leading-relaxed font-light">
        <p>
          GramPickup was created to bridge the delivery gap between cities and rural areas. Many ecommerce delivery services do not reach remote villages directly, resulting in failed deliveries, high delivery charges, or extensive travel requirements for customers to pick up their shipments.
        </p>
        
        <p>
          Our platform establishes a network of local verified city shops (like groceries or pharmacies) to act as central pickup points for villagers. Customers register their expected orders, use the verified shop addresses, and have their packages securely stored until they can retrieve them.
        </p>

        <h2 className="text-sm font-semibold uppercase tracking-wider text-black pt-4">Fee Structure</h2>
        <p>
          To compensate local shop owners for their storage space and service, we implement a transparent fee system:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Base Fee:</strong> ₹10 upon parcel arrival.</li>
          <li><strong>Storage Fee:</strong> ₹2 per day.</li>
          <li><strong>Formula:</strong> Fee = ₹10 + (Days Stored × ₹2).</li>
        </ul>

        <h2 className="text-sm font-semibold uppercase tracking-wider text-black pt-4">Security Standards</h2>
        <p>
          Each package is linked with a tracking number and requires a secure OTP generated by the shopkeeper. No parcel is handed over until the customer provides the matching OTP, ensuring packages are only received by their intended owners.
        </p>
      </div>
    </div>
  );
};

export default About;
